"use client";

import { FormEvent, useEffect, useState } from "react";
import { ShipmentStatus } from "@/components/shipment-status";
import { ShipmentTimeline } from "@/components/shipment-timeline";
import { LanguageChooser } from "@/components/language-chooser";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { type Language, translations } from "@/lib/i18n";
import { formatMoney } from "@/lib/utils";

type Order = { code: string; status: "code" | "address" | "not_sent" | "preparing" | "sent" | "delivered" | "shipping"; address: string; awb: string; awbStatus?: string | null; awbStatusDescription?: string | null; awbLastCheckedAt?: string | null; awbEvents?: Array<{ date: string | null; title: string; description: string; location: string | null }>; awbRoute?: string[]; orderPrice: number; shippingPrice: number; shippingPaid: boolean };

export default function Home() {
  const [language, setLanguage] = useState<Language>("ro"); const copy = translations[language];
  const [code, setCode] = useState(""); const [order, setOrder] = useState<Order | null>(null); const [address, setAddress] = useState(""); const [state, setState] = useState<"code" | "address" | "shipping">("code"); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false); const [trackingUnavailable, setTrackingUnavailable] = useState(false);
  useEffect(() => { const stored = window.localStorage.getItem("order-tracker-language") as Language | null; if (stored && stored in translations) setLanguage(stored); }, []);
  async function lookup(event: FormEvent) { event.preventDefault(); setMessage(""); if (!/^\d{5}$/.test(code)) return setMessage(copy.validCode); setBusy(true); try { const response = await fetch(`/api/orders?code=${code}`); const data = await response.json(); if (!response.ok) throw new Error(data.error); setOrder(data.order); setTrackingUnavailable(Boolean(data.trackingUnavailable)); setAddress(data.order.address); setState(data.order.address ? "shipping" : "address"); } catch (error) { setMessage(error instanceof Error && error.message === "Order not found." ? copy.couldNotFind : copy.serviceUnavailable); } finally { setBusy(false); } }
  async function saveAddress(event: FormEvent) { event.preventDefault(); if (!address.trim() || !order) return; setBusy(true); setMessage(""); try { const response = await fetch("/api/orders", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ code: order.code, address: address.trim() }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setOrder(data.order); setState("shipping"); } catch { setMessage(copy.saveAddressError); } finally { setBusy(false); } }
  return <main className="content-width py-8 sm:py-12"><header className="mb-16 flex items-center justify-between"><span className="text-sm font-medium tracking-tight">{copy.tracker}</span><LanguageChooser label={copy.language} value={language} onChange={setLanguage} /></header><section className="max-w-xl"><p className="mb-3 text-sm text-muted-foreground">{state === "code" ? copy.codeHint : state === "address" ? copy.addressHint : copy.shippingHint}</p><h1 className="mb-8 text-3xl font-medium tracking-tight sm:text-4xl">{state === "code" ? copy.findOrder : state === "address" ? copy.deliveryAddress : copy.shippingStatus}</h1>
    {state === "code" && <form onSubmit={lookup} className="max-w-sm space-y-3"><Label htmlFor="code">{copy.orderCode}</Label><div className="flex gap-2"><Input id="code" inputMode="numeric" autoComplete="one-time-code" maxLength={5} placeholder={copy.placeholderCode} value={code} onChange={(e) => setCode(e.target.value.replace(/\D/g, "").slice(0, 5))} autoFocus /><Button type="submit" disabled={busy || code.length !== 5}>{busy ? copy.checking : copy.continue}</Button></div></form>}
    {state === "address" && <form onSubmit={saveAddress} className="max-w-md space-y-3"><Label htmlFor="address">{copy.addressLabel}</Label><textarea id="address" rows={4} value={address} onChange={(e) => setAddress(e.target.value)} className="flex w-full resize-none rounded-md border bg-card px-3 py-3 text-sm outline-none focus-visible:ring-2 focus-visible:ring-ring" placeholder={copy.addressPlaceholder} autoFocus /><Button type="submit" disabled={busy || !address.trim()}>{busy ? copy.saving : copy.saveAddress}</Button></form>}
    {state === "shipping" && order && <div className="space-y-6">{trackingUnavailable && <p className="rounded-md border border-border bg-muted/40 px-4 py-3 text-sm text-muted-foreground">{copy.trackingUnavailable}</p>}<div className="flex items-center justify-between border-b pb-5"><div><p className="text-xs text-muted-foreground">{copy.order} {order.code}</p><h2 className="mt-1 text-xl font-medium">{copy.shipmentDetails}</h2><p className="mt-1 text-sm text-muted-foreground">{copy.shipmentDescription}</p></div><img src="/cargus-logo.png" alt="Cargus" className="h-12 w-auto object-contain" /></div><ShipmentStatus status={order.status} copy={copy} /><ShipmentTimeline events={order.awbEvents ?? []} route={order.awbRoute ?? []} latestStatus={order.awbStatus} copy={copy} /><Card><CardHeader><CardTitle>{copy.order} {order.code}</CardTitle><p className="text-sm text-muted-foreground">{copy.readyShipping}</p></CardHeader><CardContent className="space-y-6"><div className="grid gap-5 border-y py-5 sm:grid-cols-2"><div><p className="text-xs text-muted-foreground">{copy.cargusAwb}</p><p className="mt-1 text-sm">{order.awb || copy.notAssigned}</p></div><div><p className="text-xs text-muted-foreground">{copy.payment}</p><p className="mt-1 text-sm">{order.shippingPaid ? copy.shippingPaid : copy.shippingUnpaid}</p></div><div><p className="text-xs text-muted-foreground">{copy.orderPrice}</p><p className="mt-1 text-sm">{formatMoney(order.orderPrice)}</p></div><div><p className="text-xs text-muted-foreground">{copy.shippingPrice}</p><p className="mt-1 text-sm">{formatMoney(order.shippingPrice)}</p></div></div><div><p className="text-xs text-muted-foreground">{copy.deliveryAddressLabel}</p><p className="mt-1 whitespace-pre-line text-sm">{order.address}</p></div></CardContent></Card></div>}
    {message && <p role="alert" className="mt-5 text-sm text-destructive">{message}</p>}<button className="mt-16 text-xs text-muted-foreground underline decoration-border underline-offset-4" onClick={() => { setState("code"); setOrder(null); setCode(""); setMessage(""); }}>{copy.startOver}</button></section><footer className="mt-24 border-t pt-5 text-xs text-muted-foreground">{copy.needHelp}</footer></main>;
}
