"use client";

import { Check, CircleDot, Package, Truck } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { type Copy } from "@/lib/i18n";

type ShipmentStatus = "code" | "address" | "not_sent" | "preparing" | "sent" | "delivered" | "shipping";
type Event = { date: string | null; title: string; description: string; location: string | null };
function headline(status: ShipmentStatus, copy: Copy) { if (status === "not_sent") return copy.deliveryHeadlineNotSent; if (status === "delivered") return copy.deliveryHeadlineDelivered; if (status === "preparing") return copy.deliveryHeadlinePreparing; return copy.deliveryHeadline; }

export function ShipmentStatus({ status, events, rawStatus, copy }: { status: ShipmentStatus; events: Event[]; rawStatus?: string | null; copy: Copy }) {
  const normalized = status === "shipping" ? "sent" : status; const recent = events.slice(-4).reverse(); const latest = recent[0];
  return <Card className="overflow-hidden border-border/80"><CardHeader className={`${normalized === "delivered" ? "bg-emerald-50/80" : "bg-muted/30"} border-b px-5 py-6 sm:px-8`}><p className="text-2xl font-semibold tracking-tight text-foreground sm:text-3xl">{headline(normalized, copy)}</p>{latest?.date ? <p className="mt-3 text-xl font-medium text-emerald-700 sm:text-2xl">{latest.date}</p> : <p className="mt-3 text-sm text-muted-foreground">{rawStatus || copy.statusPreparing}</p>}{latest?.location && <p className="mt-2 text-sm text-muted-foreground">{latest.location}</p>}</CardHeader><CardContent className="px-5 py-6 sm:px-8">{recent.length ? <div className="space-y-0">{recent.map((event, index) => <div key={`${event.date}-${event.title}-${index}`} className="relative grid grid-cols-[7rem_1fr] gap-4 pb-7 last:pb-0 sm:grid-cols-[10rem_1fr] sm:gap-7"><div className={`text-right text-xs ${index === 0 ? "font-medium text-emerald-700" : "text-muted-foreground"}`}>{event.date || copy.dateUnavailable}{event.location && <span className="mt-1 block text-[11px]">{event.location}</span>}</div><div className="relative pl-7"><span className={`absolute left-0 top-0.5 flex h-4 w-4 items-center justify-center rounded-full border ${index === 0 ? "border-emerald-600 bg-emerald-600 text-white" : "border-border bg-card text-muted-foreground"}`}>{index === 0 ? <CircleDot className="h-2.5 w-2.5" /> : <Check className="h-2.5 w-2.5" />}</span>{index < recent.length - 1 && <span className="absolute left-[7px] top-5 h-[calc(100%-12px)] w-px bg-border" />}<p className={`text-sm ${index === 0 ? "font-medium text-foreground" : "text-muted-foreground"}`}>{event.title}</p><p className={`mt-1 text-sm leading-5 ${index === 0 ? "text-foreground" : "text-muted-foreground"}`}>{event.description}</p></div></div>)}</div> : <div className="flex gap-3 text-sm text-muted-foreground"><Package className="mt-0.5 h-4 w-4 shrink-0" /><p>{normalized === "not_sent" ? copy.statusNotSentDescription : copy.timelineUnavailable}</p></div>}</CardContent></Card>;
}
