"use client";

import { MapPin, Route, Clock3 } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { type Copy } from "@/lib/i18n";

type Event = { date: string | null; title: string; description: string; location: string | null };

export function ShipmentTimeline({ events, route, latestStatus, copy }: { events: Event[]; route: string[]; latestStatus?: string | null; copy: Copy }) {
  return <div className="space-y-6"><Card><CardHeader><CardTitle>{copy.routeTitle}</CardTitle><p className="text-sm text-muted-foreground">{copy.routeDescription}</p></CardHeader><CardContent>{route.length ? <div className="flex flex-wrap items-center gap-2 text-sm">{route.map((location, index) => <div key={`${location}-${index}`} className="flex items-center gap-2"><span className="inline-flex items-center gap-1.5 rounded-full border border-border bg-muted/40 px-3 py-1.5"><MapPin className="h-3.5 w-3.5 text-accent" />{location}</span>{index < route.length - 1 && <Route className="h-4 w-4 text-muted-foreground" />}</div>)}</div> : <p className="text-sm text-muted-foreground">{copy.routeUnavailable}</p>}</CardContent></Card><Card><CardHeader><CardTitle>{copy.timelineTitle}</CardTitle><p className="text-sm text-muted-foreground">{latestStatus || copy.timelineDescription}</p></CardHeader><CardContent>{events.length ? <div className="space-y-0">{events.map((event, index) => <div key={`${event.date}-${event.title}-${index}`} className="relative flex gap-4 pb-7 last:pb-0"><div className="flex flex-col items-center"><span className={`mt-1 h-3 w-3 rounded-full border-2 ${index === 0 ? "border-accent bg-accent" : "border-border bg-card"}`} />{index < events.length - 1 && <span className="mt-1 h-full w-px bg-border" />}</div><div className="min-w-0 flex-1"><div className="flex flex-col gap-1 sm:flex-row sm:items-baseline sm:justify-between"><p className="text-sm font-medium">{event.title}</p>{event.date && <span className="inline-flex items-center gap-1 text-xs text-muted-foreground"><Clock3 className="h-3 w-3" />{event.date}</span>}</div><p className="mt-1 text-sm leading-6 text-muted-foreground">{event.description}</p>{event.location && <p className="mt-2 inline-flex items-center gap-1.5 text-xs text-muted-foreground"><MapPin className="h-3 w-3" />{event.location}</p>}</div></div>)}</div> : <p className="text-sm text-muted-foreground">{copy.timelineUnavailable}</p>}</CardContent></Card></div>;
}
