export const languages = [
  { code: "ro", label: "Română" },
  { code: "hu", label: "Magyar" },
  { code: "en", label: "English" },
] as const;

export type Language = (typeof languages)[number]["code"];

export const translations = {
  ro: {
    tracker: "Urmărire comandă", slash: "/", codeHint: "Introdu codul comenzii pentru a continua.", addressHint: "Adaugă adresa de livrare pentru această comandă.", shippingHint: "Detaliile comenzii tale sunt mai jos.", findOrder: "Găsește comanda", deliveryAddress: "Adresa de livrare", shippingStatus: "Status livrare", orderCode: "Cod comandă", placeholderCode: "00000", checking: "Se verifică", continue: "Continuă", validCode: "Introdu codul de 5 cifre primit pentru comandă.", addressLabel: "Adresa completă de livrare", addressPlaceholder: "Stradă, oraș, cod poștal", saving: "Se salvează", saveAddress: "Salvează adresa", order: "Comanda", readyShipping: "Pregătită pentru expediere", cargusAwb: "AWB Cargus", notAssigned: "Nu a fost alocat încă", payment: "Plată", shippingPaid: "Transport plătit", shippingUnpaid: "Transport neachitat", orderPrice: "Preț comandă", shippingPrice: "Preț transport", deliveryAddressLabel: "Adresa de livrare", needHelp: "Ai nevoie de ajutor? Păstrează codul comenzii la îndemână.", startOver: "Ia-o de la capăt", couldNotFind: "Comanda nu a fost găsită.", serviceUnavailable: "Serviciul de comenzi nu este configurat.", saveAddressError: "Adresa nu a putut fi salvată.", stepCode: "Cod", stepAddress: "Adresă", stepShipping: "Livrare", language: "Limbă",
    restricted: "Zonă restricționată", adminAccess: "Acces administrator", scanCode: "Scanează sau introdu codul de acces", codeNotRecognized: "Cod nerecunoscut.", orders: "Comenzi", admin: "Administrator", manageShipping: "Gestionează livrările", newCode: "Cod nou", createCode: "Creează cod", code: "Cod", awb: "AWB", shipping: "Transport", paid: "Plătit", save: "Salvează", saveChanges: "Salvează modificările", noOrders: "Nu există încă comenzi.", lock: "Blochează", cargusPlaceholder: "AWB Cargus", couldNotCreate: "Comanda nu a putut fi creată.", couldNotUpdate: "Comanda nu a putut fi actualizată.", total: "Total",
  },
  hu: {
    tracker: "Rendeléskövető", slash: "/", codeHint: "Add meg a rendelési kódot a folytatáshoz.", addressHint: "Add meg a rendelés szállítási címét.", shippingHint: "A rendelés részletei alább láthatók.", findOrder: "Rendelés keresése", deliveryAddress: "Szállítási cím", shippingStatus: "Szállítási állapot", orderCode: "Rendelési kód", placeholderCode: "00000", checking: "Ellenőrzés", continue: "Folytatás", validCode: "Add meg a rendeléshez kapott 5 jegyű kódot.", addressLabel: "Teljes szállítási cím", addressPlaceholder: "Utca, város, irányítószám", saving: "Mentés", saveAddress: "Cím mentése", order: "Rendelés", readyShipping: "Szállításra kész", cargusAwb: "Cargus AWB", notAssigned: "Még nincs megadva", payment: "Fizetés", shippingPaid: "Szállítás kifizetve", shippingUnpaid: "Szállítás nincs kifizetve", orderPrice: "Rendelés ára", shippingPrice: "Szállítás ára", deliveryAddressLabel: "Szállítási cím", needHelp: "Segítségre van szükséged? Tartsd kéznél a rendelési kódot.", startOver: "Újrakezdés", couldNotFind: "A rendelés nem található.", serviceUnavailable: "A rendelési szolgáltatás nincs beállítva.", saveAddressError: "A cím mentése nem sikerült.", stepCode: "Kód", stepAddress: "Cím", stepShipping: "Szállítás", language: "Nyelv",
    restricted: "Korlátozott terület", adminAccess: "Adminisztrátori hozzáférés", scanCode: "Olvasd be vagy írd be a hozzáférési kódot", codeNotRecognized: "A kód nem ismert.", orders: "Rendelések", admin: "Adminisztrátor", manageShipping: "Szállítások kezelése", newCode: "Új kód", createCode: "Kód létrehozása", code: "Kód", awb: "AWB", shipping: "Szállítás", paid: "Fizetve", save: "Mentés", saveChanges: "Módosítások mentése", noOrders: "Még nincsenek rendelések.", lock: "Zárolás", cargusPlaceholder: "Cargus AWB", couldNotCreate: "A rendelés létrehozása nem sikerült.", couldNotUpdate: "A rendelés frissítése nem sikerült.", total: "Összesen",
  },
  en: {
    tracker: "Order tracker", slash: "/", codeHint: "Enter your order code to continue.", addressHint: "Add the delivery address for this order.", shippingHint: "Your order details are below.", findOrder: "Find your order", deliveryAddress: "Delivery address", shippingStatus: "Shipping status", orderCode: "Order code", placeholderCode: "00000", checking: "Checking", continue: "Continue", validCode: "Enter the 5-digit code from your order.", addressLabel: "Full delivery address", addressPlaceholder: "Street, city, postal code", saving: "Saving", saveAddress: "Save address", order: "Order", readyShipping: "Ready for shipping", cargusAwb: "Cargus AWB", notAssigned: "Not assigned yet", payment: "Payment", shippingPaid: "Shipping paid", shippingUnpaid: "Shipping unpaid", orderPrice: "Order price", shippingPrice: "Shipping price", deliveryAddressLabel: "Delivery address", needHelp: "Need help? Keep your order code handy.", startOver: "Start over", couldNotFind: "Order not found.", serviceUnavailable: "Order service is not configured.", saveAddressError: "Could not save your address.", stepCode: "Code", stepAddress: "Address", stepShipping: "Shipping", language: "Language",
    restricted: "Restricted area", adminAccess: "Admin access", scanCode: "Scan or enter access code", codeNotRecognized: "Code not recognized.", orders: "Orders", admin: "Admin", manageShipping: "Manage shipping", newCode: "New code", createCode: "Create code", code: "Code", awb: "AWB", shipping: "Shipping", paid: "Paid", save: "Save", saveChanges: "Save changes", noOrders: "No orders yet.", lock: "Lock", cargusPlaceholder: "Cargus AWB", couldNotCreate: "Could not create the order.", couldNotUpdate: "Could not update the order.", total: "Total",
  },
} as const;

export type Copy = { [Key in keyof typeof translations.ro]: string };
